websocket:
  host: neon-messagebus
gui_websocket:
  host: neon-gui
gui:
  idle_display_skill: skill-homescreen-lite.openvoiceos
ready_settings:
  - skills
  - speech
  - audio
  - gui
skills:
  default_skills:
    # Jokes skill included because it cannot be pip installed to the image
    - https://github.com/JarbasSkills/skill-icanhazdadjokes/tree/dev
MQ:
  server: mq.2021.us
  port: 25672
TTS:
  neon-tts-plugin-audiofiles:
    audio_file_path: /xdg/data/neon/AudioFileTTS