skills:
  essential_skills: []
  default_skills: https://raw.githubusercontent.com/NeonGeckoCom/neon_skills/FIX_UpdateDockerSkillBranches/skill_lists/DEFAULT-SKILLS-DOCKER
  skill_manager: osm
dirVars:
  skillsDir: /root/.local/share/neon/skills

websocket:
  host: neon-messagebus
  port: 8181

gui:
  host: neon-gui
  port: 18181
