version: '3.1'
networks:
  neon-core:
volumes:
  xdg:
    driver_opts:
      type: xdg
      o: bind
      device: ${NEON_XDG_PATH}
services:
  neon-messagebus:
    container_name: neon-messagebus
    image: ghcr.io/neongeckocom/neon_messagebus:dev
    ports:
    - "8181:8181"
    networks:
      neon-core:
        aliases:
        - messagebus
    volumes:
    - xdg:/xdg:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - XDG_CONFIG_HOME=/xdg/config
    - XDG_DATA_HOME=/xdg/data
    - XDG_CACHE_HOME=/xdg/cache
    - XDG_STATE_HOME=/xdg/state
  neon-speech:
    container_name: neon-speech
    image: ghcr.io/neongeckocom/neon_speech:dev
    networks:
    - neon-core
    volumes:
    - ~/.config/pulse/cookie:/tmp/pulse_cookie:ro
    - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    - xdg:/xdg:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - PULSE_COOKIE=/tmp/pulse_cookie
    - XDG_CONFIG_HOME=/xdg/config
    - XDG_DATA_HOME=/xdg/data
    - XDG_CACHE_HOME=/xdg/cache
    - XDG_STATE_HOME=/xdg/state
    devices:
    - /dev/snd:/dev/snd
  neon-skills:
    container_name: neon-skills
    image: ghcr.io/neongeckocom/neon_skills-default_skills:dev
    networks:
    - neon-core
    volumes:
    - ~/.config/pulse/cookie:/tmp/pulse_cookie:ro
    - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    - ${NEON_SKILLS_DIR}:/skills:ro
    - xdg:/xdg:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - PULSE_COOKIE=/tmp/pulse_cookie
    - XDG_CONFIG_HOME=/xdg/config
    - XDG_DATA_HOME=/xdg/data
    - XDG_CACHE_HOME=/xdg/cache
    - XDG_STATE_HOME=/xdg/state
    devices:
    - /dev/snd:/dev/snd
  neon-audio:
    container_name: neon-audio
    image: ghcr.io/neongeckocom/neon_audio:dev
    networks:
    - neon-core
    volumes:
    - ~/.config/pulse/cookie:/tmp/pulse_cookie:ro
    - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    - /run/dbus/system_dbus_socket:/run/dbus/system_dbus_socket:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - xdg:/xdg:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - PULSE_COOKIE=/tmp/pulse_cookie
    - DISPLAY=${DISPLAY}
    - XDG_CONFIG_HOME=/xdg/config
    - XDG_DATA_HOME=/xdg/data
    - XDG_CACHE_HOME=/xdg/cache
    - XDG_STATE_HOME=/xdg/state
    devices:
    - /dev/snd:/dev/snd
  neon-gui:
    container_name: neon-gui
    image: ghcr.io/neongeckocom/neon_gui:dev
    networks:
      neon-core:
        aliases:
        - gui
    ports:
    - "18181:18181"
    - "8000:8000"
    volumes:
    - xdg:/xdg:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - XDG_CONFIG_HOME=/xdg/config
    - XDG_DATA_HOME=/xdg/data
    - XDG_CACHE_HOME=/xdg/cache
    - XDG_STATE_HOME=/xdg/state
  neon-enclosure:
    container_name: neon-enclosure
    image: ghcr.io/neongeckocom/neon_enclosure:dev
    networks:
    - neon-core
    volumes:
    - ~/.config/pulse/cookie:/tmp/pulse_cookie:ro
    - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    - /run/dbus/system_dbus_socket:/run/dbus/system_dbus_socket:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - xdg:/xdg:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - PULSE_COOKIE=/tmp/pulse_cookie
    - DISPLAY=${DISPLAY}
    - XDG_CONFIG_HOME=/xdg/config
    - XDG_DATA_HOME=/xdg/data
    - XDG_CACHE_HOME=/xdg/cache
    - XDG_STATE_HOME=/xdg/state
    devices:
    - /dev/snd:/dev/snd